[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py312"
select = ["E", "F", "I", "UP"]
ignore = []
fix = true

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.12"
strict = false
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
warn_return_any = true
