// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournametsService.Data;

#nullable disable

namespace TournametsService.Migrations
{
    [DbContext(typeof(TournametsDbContext))]
    partial class TournametsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TournametsService.Models.BracketMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExternalMatchId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SlotIndex")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TournamentId");

                    b.ToTable("BracketMatches");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            GroupId = 1,
                            Label = "Ronda grupal 1",
                            Round = "group",
                            SlotIndex = 0,
                            Status = "scheduled",
                            TournamentId = "cup2025"
                        },
                        new
                        {
                            Id = 1002,
                            GroupId = 1,
                            Label = "Ronda grupal 2",
                            Round = "group",
                            SlotIndex = 1,
                            Status = "scheduled",
                            TournamentId = "cup2025"
                        },
                        new
                        {
                            Id = 1003,
                            GroupId = 2,
                            Label = "Ronda grupal 1",
                            Round = "group",
                            SlotIndex = 0,
                            Status = "scheduled",
                            TournamentId = "cup2025"
                        },
                        new
                        {
                            Id = 1004,
                            GroupId = 2,
                            Label = "Ronda grupal 2",
                            Round = "group",
                            SlotIndex = 1,
                            Status = "scheduled",
                            TournamentId = "cup2025"
                        },
                        new
                        {
                            Id = 1099,
                            Label = "Final",
                            Round = "final",
                            Status = "scheduled",
                            TournamentId = "cup2025"
                        });
                });

            modelBuilder.Entity("TournametsService.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Key")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#7c3aed",
                            Key = "group-a",
                            Name = "GRUPO A",
                            TournamentId = "cup2025"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#a21caf",
                            Key = "group-b",
                            Name = "GRUPO B",
                            TournamentId = "cup2025"
                        });
                });

            modelBuilder.Entity("TournametsService.Models.Tournament", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinalMatchId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FinalMatchId");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            Id = "cup2025",
                            Code = "cup2025",
                            Location = "Arena Nacional",
                            Name = "Copa 2025",
                            Season = "2025",
                            UpdatedUtc = new DateTime(2025, 11, 1, 18, 58, 30, 392, DateTimeKind.Utc).AddTicks(3797),
                            Venue = "Estadio Principal"
                        });
                });

            modelBuilder.Entity("TournametsService.Models.BracketMatch", b =>
                {
                    b.HasOne("TournametsService.Models.Group", "Group")
                        .WithMany("Matches")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TournametsService.Models.Tournament", "Tournament")
                        .WithMany("BracketMatches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournametsService.Models.Group", b =>
                {
                    b.HasOne("TournametsService.Models.Tournament", "Tournament")
                        .WithMany("Groups")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournametsService.Models.Tournament", b =>
                {
                    b.HasOne("TournametsService.Models.BracketMatch", "FinalMatch")
                        .WithMany()
                        .HasForeignKey("FinalMatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FinalMatch");
                });

            modelBuilder.Entity("TournametsService.Models.Group", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("TournametsService.Models.Tournament", b =>
                {
                    b.Navigation("BracketMatches");

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
